// This file is machine generated by EncodingTestGen.py at Thu Apr 30 21:52:45 2020. DO NOT EDIT.
#ifndef TEST_UTILS_ENCODINGTEST_UTF32_INVALID_H
#define TEST_UTILS_ENCODINGTEST_UTF32_INVALID_H

const char Data[] = {
    static_cast<char>(0xE2),
    static_cast<char>(0x70),
    static_cast<char>(0x42),
    static_cast<char>(0x51),
    static_cast<char>(0x96),
    static_cast<char>(0xB8),
    static_cast<char>(0xAB),
    static_cast<char>(0xDA),
    static_cast<char>(0x80),
    static_cast<char>(0x8E),
    static_cast<char>(0xB4),
    static_cast<char>(0xA3),
    static_cast<char>(0x47),
    static_cast<char>(0x2D),
    static_cast<char>(0xCA),
    static_cast<char>(0xBC),
    static_cast<char>(0x95),
    static_cast<char>(0xA6),
    static_cast<char>(0x6F),
    static_cast<char>(0x16),
    static_cast<char>(0x8E),
    static_cast<char>(0x03),
    static_cast<char>(0xE4),
    static_cast<char>(0x9B),
    static_cast<char>(0x74),
    static_cast<char>(0x14),
    static_cast<char>(0xCF),
    static_cast<char>(0xF5),
    static_cast<char>(0x36),
    static_cast<char>(0x4B),
    static_cast<char>(0x62),
    static_cast<char>(0x2A),
    static_cast<char>(0x04),
};

#endif // TEST_UTILS_ENCODINGTEST_UTF32_INVALID_H