#
#  shared.py
#  - Shared functions among generators.
#
#  Copyright (c) 2019~2021 numver8638(신진환, Jinhwan Shin)
#  Released under the MIT License.
#  See the LICENSE file in the project root to get more information.
#
from contextlib import contextmanager
from os.path import dirname
import time


PROJECT_ROOT = dirname(dirname(__file__))


@contextmanager
def header(filename, generator, include_guard):
    """
    Create header file with include guard.

    :param filename: name of the file.
    :param generator: name of the generator.
    :param include_guard: string to use in include guard.
    :return: file object.
    """
    file = None

    try:
        file = open(filename, 'w', newline='\n')

        file.write(
            '// This file is machine generated by {0} at {1}. DO NOT EDIT.\n'.format(generator, time.asctime())
        )

        file.write(
            '#ifndef {0}\n#define {0}\n\n'.format(include_guard)
        )

        yield file

        file.write('\n#endif // {0}'.format(include_guard))
    finally:
        if file is not None:
            file.close()
