# Identifiers
ID
id
Id
iD
id_1
id_2

# Numbers
0
123
0b1010
0B0101
0o777
0O777
0x1f4d
0X1Fe3
0.123
123e7
123E7
123e-7
123E-7
123e+7
123E+7
0.123e7
0.123E7
0.123e-7
0.123E-7
0.123e+7
0.123E+7

# Strings
''
'single quoted string'
'single quoted interpolated string: $value and ${CallSomething().CallAnother("argument")}'
'single quoted string with escape sequences: \a\b\f\n\r\t\v\'\"\$\x42\uAC00\U0000AC00'
""
"double quoted string"
"double quoted interpolated string: $value and ${CallSomething().CallAnother('argument')}"
"double quoted string with escape sequences: \a\b\f\n\r\t\v\'\"\$\x42\uAC00\U0000AC00"

# Keywords
and
as
assert
case
class
continue
def
default
defined
deinit
dependsOn
do
doFirst
doLast
break
else
except
export
extends
false
finally
for
from
get
if
import
in
init
inputs
is
match
none
not
operator
or
outputs
pass
raise
return
self
set
static
super
task
true
try

var
while
with

# Punctuators
+
+=
-
-=
*
*=
/
/=
%
%=
&
&=
|
|=
~
^
^=
<
<=
<<
<<=
>
>=
>>
>>=
==
!=
=
,
:
.
...
=>
(
)
{
}
[
]